In [1]:
import pandas as pd

In [2]:
import textstat

In [40]:
prompts_dataset= pd.read_csv('/Users/rakshitha/Downloads/Prompts_Eval.csv')

In [41]:
len(prompts_dataset)
prompts_dataset.head(10)

                                             Prompts  Responses
0  Once upon a time there was an old mother pig w...        NaN
1  One day her mother said to her, "Come, Little ...        NaN
2  I have a cat and dog and they always fight wit...        NaN
3  Today, I have a few tasks to complete. I need ...        NaN
4  When you think of a podcast script, you might ...        NaN
5  My job is to help people communicate better in...        NaN
6  At my workplace, there was a story about a new...        NaN
7  People have a wide range of activities that th...        NaN
8  Once there was a little girl named Sophie who ...        NaN
9  One well-known children's book is "The Cat in ...        NaN

In [9]:
prompts_dataset["Prompts"]

0     Once upon a time there was an old mother pig w...
1     One day her mother said to her, "Come, Little ...
2     I have a cat and dog and they always fight wit...
3     Today, I have a few tasks to complete. I need ...
4     When you think of a podcast script, you might ...
5     My job is to help people communicate better in...
6     At my workplace, there was a story about a new...
7     People have a wide range of activities that th...
8     Once there was a little girl named Sophie who ...
9     One well-known children's book is "The Cat in ...
10    Oh God... well, it started about a half hour b...
11    Rachel Green is a fictional character from the...
12    There are, indeed, only two possible outcomes:...
13    My favourite colour is the colour blue. Blue c...
14    Cooking a steak is something that every man sh...
15    The Messi versus Ronaldo debate is one that is...
16    Playing top lane in League of Legends can be p...
17    When buying a laptop, there is a lot to take i...
18    Planning a wedding can be chaotic. There are a...
19    Do you like to play games? I love to play game...
20    My favorite sport is soccer. I love to kick th...
21    My favorite kind of music is pop. I love to li...
22    A car is a vehicle that is used for transporta...
23    As the coach, it's my job to prepare my team f...
24    Climate change is a major global problem that ...
25    Hitler was born in Austria in 1889 and grew up...
26    Once upon a time, in a far-off kingdom, there ...
27    You had three weeks. The universe was created ...
28    I had always heard your entire life flashes in...
29    I like to listen to podcasts. I listen to stuf...
30    Also an English professor: without a PhD it is...
31    For pets the prices for services surrounding d...
32    You know, despite all the bullshit that comes ...
33    Hi there! I'm a big fan of the game League of ...
34    A brother and sister named Hansel and Gretel l...
35    Because I’ve been to a million auditions and t...
36    I'm a big fan of cheese. It's so yummy and the...
37    I been standing with you! I been right here wi...
38    I’m gonna stop you there. When you do this for...
39    I went to New York to meet a director for a sp...
40    My sister is so cool. She is older than me by ...
41    But then the farther away I got from that and ...
42    I always wanted to be in the movies. When I wa...
43    I have moved to a small oceanside town. My mot...
44    My parents were married fairly young and they ...
45    I’m 32, and I’m here celebrating the fact that...
46    Raised in an orphanage, I know nothing of my m...
47    Hi there! Are you thinking about buying legos?...
48    I dream about flying. Not really flying. More ...
49    This is really fascinating, what’s going on at...
50    Animals are so cool! There are so many differe...
51    OSRS stands for Old School RuneScape. It's a p...
52    When I was 16, I lived with the Watkins family...
53    Hey there! Have you heard of One Piece? It's a...
54    Moby Dick is a really old book that was writte...
55    There’s a big difference between asking a huma...
56    Social anxiety becomes problematic when it beg...
57    My birthday party was so much fun! I invited a...
58    It's easy to tell when someone's not paying at...
Name: Prompts, dtype: object

In [37]:
prompts_df = pd.DataFrame(prompts_dataset)
prompts_df= prompts_df['Prompts']
prompts_df.columns=['Prompts']
prompts_df = prompts_df.to_frame('Prompts')
prompts_df['readability_consensus'] = prompts_df['Prompts'].apply(textstat.text_standard, float_output=False)
prompts_df['readability_score'] = prompts_df['Prompts'].apply(textstat.dale_chall_readability_score)

In [38]:
prompts_df.head(5)

,Prompts,readability_consensus,readability_score
0,Once upon a time there was an old mother pig w...,5th and 6th grade,5.95
1,"One day her mother said to her, ""Come, Little ...",7th and 8th grade,1.59
2,I have a cat and dog and they always fight wit...,5th and 6th grade,6.17
3,"Today, I have a few tasks to complete. I need ...",6th and 7th grade,6.76
4,"When you think of a podcast script, you might ...",7th and 8th grade,7.70
5,My job is to help people communicate better in...,6th and 7th grade,7.07
6,"At my workplace, there was a story about a new...",7th and 8th grade,8.13
7,People have a wide range of activities that th...,8th and 9th grade,8.24
8,Once there was a little girl named Sophie who ...,5th and 6th grade,5.87
9,"One well-known children's book is ""The Cat in ...",7th and 8th grade,7.68

In [39]:
beginner_dataset_df = prompts_df[prompts_df['readability_score'] <= 6.99]
beginner_dataset_df = beginner_dataset_df['Prompts']
beginner_dataset_df = beginner_dataset_df.to_frame('Prompts')
beginner_dataset_df['readability_score'] = beginner_dataset_df['Prompts'].apply(textstat.dale_chall_readability_score)
beginner_dataset_df.to_csv('begprompts_dataset.csv',encoding='utf-8',index=False)
beginner_dataset_df.head(30)

                                              Prompts  readability_score
0   Once upon a time there was an old mother pig w...               5.95
1   One day her mother said to her, "Come, Little ...               1.59
2   I have a cat and dog and they always fight wit...               6.17
3   Today, I have a few tasks to complete. I need ...               6.76
8   Once there was a little girl named Sophie who ...               5.87
10  Oh God... well, it started about a half hour b...               6.61
13  My favourite colour is the colour blue. Blue c...               5.72
19  Do you like to play games? I love to play game...               5.44
20  My favorite sport is soccer. I love to kick th...               5.49
21  My favorite kind of music is pop. I love to li...               6.61
26  Once upon a time, in a far-off kingdom, there ...               6.82
27  You had three weeks. The universe was created ...               6.27
29  I like to listen to podcasts. I listen to stuf...               5.60
32  You know, despite all the bullshit that comes ...               5.97
33  Hi there! I'm a big fan of the game League of ...               6.08
34  A brother and sister named Hansel and Gretel l...               5.70
35  Because I’ve been to a million auditions and t...               6.51
36  I'm a big fan of cheese. It's so yummy and the...               6.75
37  I been standing with you! I been right here wi...               6.06
39  I went to New York to meet a director for a sp...               6.83
40  My sister is so cool. She is older than me by ...               6.66
41  But then the farther away I got from that and ...               6.14
42  I always wanted to be in the movies. When I wa...               5.85
43  I have moved to a small oceanside town. My mot...               6.70
44  My parents were married fairly young and they ...               6.62
47  Hi there! Are you thinking about buying legos?...               6.47
48  I dream about flying. Not really flying. More ...               5.88
50  Animals are so cool! There are so many differe...               6.33
53  Hey there! Have you heard of One Piece? It's a...               6.58
54  Moby Dick is a really old book that was writte...               6.61

In [32]:
advanced_dataset_df = prompts_df[prompts_df['readability_score'] > 6.99]
advanced_dataset_df= advanced_dataset_df['Prompts']
advanced_dataset_df= advanced_dataset_df.to_frame('Prompts')
advanced_dataset_df['readability_score'] = advanced_dataset_df['Prompts'].apply(textstat.dale_chall_readability_score)
advanced_dataset_df.to_csv('advprompts_dataset.csv',encoding='utf-8',index=False)
advanced_dataset_df.head(30)

                                              Prompts  readability_score
4   When you think of a podcast script, you might ...               7.70
5   My job is to help people communicate better in...               7.07
6   At my workplace, there was a story about a new...               8.13
7   People have a wide range of activities that th...               8.24
9   One well-known children's book is "The Cat in ...               7.68
11  Rachel Green is a fictional character from the...               9.58
12  There are, indeed, only two possible outcomes:...               8.27
14  Cooking a steak is something that every man sh...               7.30
15  The Messi versus Ronaldo debate is one that is...               9.94
16  Playing top lane in League of Legends can be p...               8.26
17  When buying a laptop, there is a lot to take i...               7.70
18  Planning a wedding can be chaotic. There are a...               7.35
22  A car is a vehicle that is used for transporta...               7.04
23  As the coach, it's my job to prepare my team f...               8.13
24  Climate change is a major global problem that ...               9.30
25  Hitler was born in Austria in 1889 and grew up...              10.08
28  I had always heard your entire life flashes in...               7.23
30  Also an English professor: without a PhD it is...               8.06
31  For pets the prices for services surrounding d...               8.74
38  I’m gonna stop you there. When you do this for...               7.30
45  I’m 32, and I’m here celebrating the fact that...               8.31
46  Raised in an orphanage, I know nothing of my m...               7.05
49  This is really fascinating, what’s going on at...               8.17
51  OSRS stands for Old School RuneScape. It's a p...               7.11
52  When I was 16, I lived with the Watkins family...               7.06
55  There’s a big difference between asking a huma...               8.03
56  Social anxiety becomes problematic when it beg...               7.66
58  It's easy to tell when someone's not paying at...               9.40